import Zeta7Proof.N4ConnectionSeven

/-! Constant spanning of the primitive quotient. Rather than postulating a
constant basis, we prove descent by induction on dimension using the already
proved minimal-support constant-vector lemma. -/
noncomputable section
set_option autoImplicit false
set_option backward.isDefEq.respectTransparency.types false
open scoped RatFunc
namespace Zeta7Germ

def constantSpan (S : Submodule (RatFunc ℂ) (Fin 3 → RatFunc ℂ)) :
    Submodule (RatFunc ℂ) (Fin 3 → RatFunc ℂ) :=
  Submodule.span (RatFunc ℂ)
    {v | ∃ a : Fin 3 → ℂ, v = (fun i => RatFunc.C (a i)) ∧ v ∈ S}

theorem constantSpan_le (S : Submodule (RatFunc ℂ) (Fin 3 → RatFunc ℂ)) :
    constantSpan S ≤ S := by
  apply Submodule.span_le.mpr
  rintro v ⟨a, ha, hv⟩
  exact hv

theorem constantSpan_mono {S T : Submodule (RatFunc ℂ) (Fin 3 → RatFunc ℂ)}
    (h : T ≤ S) : constantSpan T ≤ constantSpan S := by
  apply Submodule.span_mono
  rintro v ⟨a, ha, hv⟩
  exact ⟨a, ha, h hv⟩

def coordinateKernel (S : Submodule (RatFunc ℂ) (Fin 3 → RatFunc ℂ)) (j : Fin 3) :
    Submodule (RatFunc ℂ) (Fin 3 → RatFunc ℂ) := S ⊓ LinearMap.ker (LinearMap.proj j)

theorem coordinateKernel_stable (S : Submodule (RatFunc ℂ) (Fin 3 → RatFunc ℂ))
    (hs : ∀ v ∈ S, (fun i => rationalD (v i)) ∈ S) (j : Fin 3) :
    ∀ v ∈ coordinateKernel S j, (fun i => rationalD (v i)) ∈ coordinateKernel S j := by
  rintro v ⟨hv, hj⟩
  refine ⟨hs v hv, ?_⟩
  change v j = 0 at hj
  change rationalD (v j) = 0
  rw [hj, map_zero]

/-- Every rational subspace stable under componentwise Euler differentiation
is generated by its constant vectors. This is proved, not a descent premise. -/
theorem constantSpan_eq_of_stable (S : Submodule (RatFunc ℂ) (Fin 3 → RatFunc ℂ))
    (hs : ∀ v ∈ S, (fun i => rationalD (v i)) ∈ S) : constantSpan S = S := by
  suffices ∀ n : ℕ, ∀ T : Submodule (RatFunc ℂ) (Fin 3 → RatFunc ℂ),
      Module.finrank (RatFunc ℂ) T = n →
      (∀ v ∈ T, (fun i => rationalD (v i)) ∈ T) → constantSpan T = T from
    this _ S rfl hs
  intro n
  induction n using Nat.strong_induction_on with
  | h n ih =>
    intro T hn ht
    by_cases hbot : T = ⊥
    · apply le_antisymm (constantSpan_le T)
      rw [hbot]
      exact bot_le
    obtain ⟨a, ha, ham⟩ := exists_constant_vector T hbot ht
    have hex : ∃ j : Fin 3, a j ≠ 0 := by
      by_contra h
      push_neg at h
      exact ha (funext h)
    obtain ⟨j, hj⟩ := hex
    have hc : RatFunc.C (a j) ≠ 0 := (map_ne_zero RatFunc.C).mpr hj
    have hle : coordinateKernel T j ≤ T := inf_le_left
    have hlt : coordinateKernel T j < T := by
      apply lt_of_le_of_ne hle
      intro he
      have hm : (fun i => RatFunc.C (a i)) ∈ coordinateKernel T j := by rw [he]; exact ham
      exact hc hm.2
    have hd : Module.finrank (RatFunc ℂ) (coordinateKernel T j) < n := by
      rw [← hn]
      exact Submodule.finrank_lt_finrank_of_lt hlt
    have hker := ih _ hd (coordinateKernel T j) rfl (coordinateKernel_stable T ht j)
    apply le_antisymm (constantSpan_le T)
    intro v hv
    let b : Fin 3 → RatFunc ℂ := fun i => RatFunc.C (a i)
    have hb : b ∈ constantSpan T := Submodule.subset_span ⟨a, rfl, ham⟩
    have hrem : v - (v j / b j) • b ∈ coordinateKernel T j := by
      refine ⟨T.sub_mem hv (T.smul_mem _ ham), ?_⟩
      change v j - (v j / b j) * b j = 0
      simp [b, hc]
    have hm : v - (v j / b j) • b ∈ constantSpan T :=
      constantSpan_mono hle (by rwa [hker])
    have hadd := (constantSpan T).add_mem hm ((constantSpan T).smul_mem (v j / b j) hb)
    simpa using hadd

theorem primitiveProjection_constantSpan (S : Submodule (RatFunc ℂ) SevenCoordinates)
    (hs : ∀ z ∈ S, connection7 z ∈ S) :
    constantSpan (primitiveProjection S) = primitiveProjection S :=
  constantSpan_eq_of_stable _ (primitiveProjection_stable S hs)

/-- Scalar extension preserves independence of the constant primitive vectors. -/
theorem constant_vectors_independent {ι : Type*} (a : ι → Fin 3 → ℂ)
    (ha : LinearIndependent ℂ a) :
    LinearIndependent (RatFunc ℂ) (fun j i => RatFunc.C (a j i)) := by
  exact linearIndependent_algebraMap_comp_iff.mpr ha

end Zeta7Germ
